name: build-docker-image
on:
  push:
    branches:
      - "gusqroo"
  pull_request:
    branches:
      - "gusqroo"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.1]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      working-directory: ./capstone_project/hello-world
    - name: Run tests
      run: npm test
      working-directory: ./capstone_project/hello-world
    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Push to Docker Hub & Kubernetes
      if: success()
      uses: docker/build-push-action@v4
      with:
        context: ./capstone_project/hello-world
        push: true
        tags: react-app-gusqroo:latest