name: Pipeline for capstone project
on:
  push:
    branches:
      - testworkflows
  pull_request:
      branches:
      - testworkflows
jobs:
    firstjob:
       name: Pipeline for capstone project
       runs-on: ubuntu-latest
       steps:
        - uses: actions/checkout@v1
        - name: Accediendo al proyecto 
          run: cd capstone_project/hello-world/
        - name: Instalando dependencias
          working-directory: capstone_project/hello-world/
          run: npm install
        - name: Corriendo test
          working-directory: capstone_project/hello-world/
          run: npm test
          if: ${{ success() }}
        - name: Building the container
          working-directory: capstone_project/hello-world/
          run: docker compose up -d
