name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      working-directory: ./capstone_project/hello-world
      run: npm ci

    - name: Run tests
      working-directory: ./capstone_project/hello-world
      run: npm test

  build-and-run-container:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ job.status == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: ./capstone_project/hello-world
      run: docker build -t hello-world .

    - name: Run Docker container
      working-directory: ./capstone_project/hello-world
      run: docker run -p 3000:3000 hello-world
